apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5175
      targetPort: 5175
  type: NodePort
  nodePort: 31000
