replicaCount: 1

image:
  backend: "shreybatra/sample-backend"
  frontend: "shreybatra/sample-frontend"
  redis: "redis"

service:
  backend:
    type: ClusterIP
    port: 8000
  frontend:
    type: NodePort
    port: 5175
    nodePort: 31000
  redis:
    type: ClusterIP
    port: 6379
